#!/bin/bash
# Deploy MockUSDC with proper treasury cap management
# This script ensures reproducible deployments

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "MockUSDC Deployment Script"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# 1. Check network
NETWORK="${SUI_NETWORK:-localnet}"
echo "Network: $NETWORK"
echo ""

# 2. Get treasury owner address (for minting)
TREASURY_OWNER="${TREASURY_OWNER_ADDRESS:-$(sui client active-address)}"
echo "Treasury Owner (for faucet): $TREASURY_OWNER"
echo ""

# 3. Check if already deployed
DEPLOYED_PACKAGE=$(cat "$PROJECT_ROOT/move/mock_usdc/.deployed" 2>/dev/null || echo "")
if [ -n "$DEPLOYED_PACKAGE" ]; then
  echo "⚠️  MockUSDC already deployed: $DEPLOYED_PACKAGE"
  read -p "Redeploy? (y/N) " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Using existing deployment"
    exit 0
  fi
fi

# 4. Switch to correct network
echo "Switching to $NETWORK..."
sui client switch --env testnet > /dev/null 2>&1  # Always use testnet for build

# 5. Deploy MockUSDC
echo "Deploying MockUSDC..."
cd "$PROJECT_ROOT/move/mock_usdc"

DEPLOY_OUTPUT=$(sui move test-publish --gas-budget 100000000 2>&1)
PACKAGE_ID=$(echo "$DEPLOY_OUTPUT" | grep "PackageID:" | awk '{print $2}')
TREASURY_CAP=$(echo "$DEPLOY_OUTPUT" | grep "TreasuryCap" | grep "ObjectID:" | awk '{print $2}')

if [ -z "$PACKAGE_ID" ]; then
  echo "❌ Deployment failed"
  echo "$DEPLOY_OUTPUT"
  exit 1
fi

echo "✅ MockUSDC deployed!"
echo "  Package ID:    $PACKAGE_ID"
echo "  Treasury Cap:  $TREASURY_CAP"
echo ""

# 6. Save deployment info
cat > "$PROJECT_ROOT/move/mock_usdc/.deployed" << EOF
# MockUSDC Deployment Info (auto-generated)
PACKAGE_ID=$PACKAGE_ID
TREASURY_CAP=$TREASURY_CAP
TREASURY_OWNER=$TREASURY_OWNER
COIN_TYPE=${PACKAGE_ID}::mock_usdc::MOCK_USDC
DEPLOYED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
NETWORK=$NETWORK
EOF

# 7. Update facilitator .env
echo "Updating facilitator .env..."
if grep -q "^MOCK_USDC_PACKAGE=" "$PROJECT_ROOT/facilitator/.env" 2>/dev/null; then
  sed -i "s|^MOCK_USDC_PACKAGE=.*|MOCK_USDC_PACKAGE=$PACKAGE_ID|" "$PROJECT_ROOT/facilitator/.env"
  sed -i "s|^MOCK_USDC_TREASURY_CAP=.*|MOCK_USDC_TREASURY_CAP=$TREASURY_CAP|" "$PROJECT_ROOT/facilitator/.env"
else
  echo "" >> "$PROJECT_ROOT/facilitator/.env"
  echo "# MockUSDC (auto-generated by deploy script)" >> "$PROJECT_ROOT/facilitator/.env"
  echo "MOCK_USDC_PACKAGE=$PACKAGE_ID" >> "$PROJECT_ROOT/facilitator/.env"
  echo "MOCK_USDC_TREASURY_CAP=$TREASURY_CAP" >> "$PROJECT_ROOT/facilitator/.env"
fi

# 8. Treasury cap ownership
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Treasury Cap Ownership"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Treasury cap is owned by: $(sui client active-address)"
echo ""
echo "⚠️  IMPORTANT: Treasury owner must have TREASURY_OWNER_PRIVATE_KEY set in facilitator/.env"
echo "   This address will be used for minting in the /fund endpoint"
echo ""
echo "Security Model:"
echo "  - Deployer:    Owns treasury cap (can mint for faucet)"
echo "  - Facilitator: Sponsors gas, receives fees (NO minting)"
echo "  - Buyer:       Holds USDC, makes payments"
echo "  - Merchant:    Receives payments"
echo ""

# 9. Summary
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Deployment Complete"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Next steps:"
echo "  1. Ensure TREASURY_OWNER_PRIVATE_KEY is set in facilitator/.env"
echo "  2. Restart facilitator: npm run dev"
echo "  3. Run tests: npm test"
echo ""
echo "Deployment info saved to: move/mock_usdc/.deployed"
echo ""
